<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1"
	passed="1">
	<reporter-output>
	</reporter-output>
	<suite name="Default suite" duration-ms="22732" started-at="2017-11-01T15:08:18Z"
		finished-at="2017-11-01T15:08:41Z">
		<groups>
		</groups>
		<test name="Default test" duration-ms="22732" started-at="2017-11-01T15:08:18Z"
			finished-at="2017-11-01T15:08:41Z">
			<class name="Testcases.Loginapplication">
				<test-method status="PASS"
					signature="Login()[pri:0, instance:Testcases.Loginapplication@50c87b21]"
					name="Login" duration-ms="22462" started-at="2017-11-01T15:08:18Z"
					finished-at="2017-11-01T15:08:41Z">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- Login -->
				<test-method status="FAIL"
					signature="tearDown(org.testng.ITestResult)[pri:0, instance:Testcases.Loginapplication@50c87b21]"
					name="tearDown" is-config="true" duration-ms="242" started-at="2017-11-01T15:08:41Z"
					finished-at="2017-11-01T15:08:41Z">
					<params>
						<param index="0">
							<value>
                <![CDATA[[TestResult name=Login status=SUCCESS method=Loginapplication.Login()[pri:0, instance:Testcases.Loginapplication@50c87b21] output={null}]]]>
							</value>
						</param>
					</params>
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Testcases.Loginapplication.tearDown(Loginapplication.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- tearDown -->
			</class> <!-- Testcases.Loginapplication -->
		</test> <!-- Default test -->
	</suite> <!-- Default suite -->
</testng-results>
